добавлены вспомогательные функции
htmlacademy-javascript/1913849-keksobooking-24 pull request #2
Opened 2021-09-29 15:12 UTC by iraratry

2021-09-29 15:21 UTC, VAnastasia requested changes

2021-09-29 15:21 UTC, VAnastasia commented on js/main.js
> +    const randCoordinates = minCoord + Math.random() * (maxCoord + 1 - minCoord);
+1 не надо добавлять, const randCoordinates = minCoord + Math.random() * (maxCoord - minCoord);

2021-09-29 15:21 UTC, VAnastasia commented on js/main.js
> +    return randCoordinates.toFixed(digitsAfter);
toFixed превращает число в строку, надо преобразовать randCoordinates.toFixed(digitsAfter) обратно в число. например, с помощью Number

2021-09-29 17:11 UTC, iraratry commented on js/main.js
> +    const randCoordinates = minCoord + Math.random() * (maxCoord + 1 - minCoord);
А в первой функции (строка 4) в аналогичной ситуации тоже +1 не надо добавлять?

2021-09-30 01:30 UTC, VAnastasia commented on js/main.js
> +    const randCoordinates = minCoord + Math.random() * (maxCoord + 1 - minCoord);
В первой функции надо

2021-09-30 08:38 UTC, merged